version: '3.7'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    platform: linux/amd64
    container_name: clickhouse
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:${CLICKHOUSE_HTTP_PORT}"
      - "${CLICKHOUSE_TCP_PORT}:${CLICKHOUSE_TCP_PORT}"
      - "${CLICKHOUSE_NATIVE_TCP_PORT}:${CLICKHOUSE_NATIVE_TCP_PORT}"
    volumes:
      - ./config:/etc/clickhouse-server
      - ./initdb:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - clickhouse-net

networks:
  clickhouse-net:
