version: '3.7'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:${CLICKHOUSE_HTTP_PORT}"
      - "${CLICKHOUSE_TCP_PORT}:${CLICKHOUSE_TCP_PORT}"
      - "${CLICKHOUSE_NATIVE_TCP_PORT}:${CLICKHOUSE_NATIVE_TCP_PORT}"
    volumes:
      - ./config:/etc/clickhouse-server
      - ./initdb:/docker-entrypoint-initdb.d
    env_file:
      - .env
    command: ["clickhouse-server", "--config-file=/etc/clickhouse-server/config.xml"]
